stages:
  - build
  - deploy
before_script:
  - export DPS_DIR=${PWD}/department-service
  - export EPS_DIR=${PWD}/employee-service
  - export OGS_DIR=${PWD}/organization-service
  - echo $DPS_DIR
  - echo $EPS_DIR
  - echo $OGS_DIR
  - echo docker info

maven-build:
  image: maven:3-jdk-11
  stage: build
  script:
    - cd $DPS_DIR
    - mvn clean
    - mvn install
    - cd $EPS_DIR
    - mvn clean
    - mvn install
    - cd $OGS_DIR
    - mvn clean
    - mvn install
  tags:
    - maytinh
  only:
    - main
  artifacts:
    expire_in: 2 weeks
    paths:
      - Rest/department-service/target/
      - Rest/employee-service/target/
      - Rest/organization-service/target/
